version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=movie_expert
    ports:
      - '3535:5432'
    volumes: 
      - ./sql/database.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - network
volumes:
  db:
    driver: local
networks:
  network:
    driver: bridge